language: java
jdk: oraclejdk8
# Run on a dedicated Trusty VM to avoid random problems like "User limit of inotify watches reached"
sudo: required
dist: trusty

services:
  - docker

before_install: ./.travis.before_install.sh

# Skip the installation step.
# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true

script: ./.travis.script.sh

deploy:
  - provider: script
    script: ./.travis.deploy.sh
    skip_cleanup: true
    on:
      branch: master

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
  - demo-hello-world-template/driver
before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/flow
  - rm -rf $HOME/.m2/repository/com/vaadin/flow-*

