package com.vaadin.hummingbird.twitter;

import java.util.Random;

public class RandomData {
    static String[] avatars = new String[] { "men/0.jpg", "men/11.jpg",
            "men/14.jpg", "men/15.jpg", "men/16.jpg", "men/17.jpg",
            "men/19.jpg", "men/2.jpg", "men/20.jpg", "men/23.jpg", "men/24.jpg",
            "men/25.jpg", "men/26.jpg", "men/27.jpg", "men/28.jpg",
            "men/29.jpg", "men/3.jpg", "men/34.jpg", "men/37.jpg", "men/39.jpg",
            "men/4.jpg", "men/40.jpg", "men/41.jpg", "men/42.jpg", "men/45.jpg",
            "men/46.jpg", "men/47.jpg", "men/48.jpg", "men/49.jpg", "men/5.jpg",
            "men/50.jpg", "men/52.jpg", "men/54.jpg", "men/55.jpg",
            "men/57.jpg", "men/58.jpg", "men/59.jpg", "men/6.jpg", "men/61.jpg",
            "men/62.jpg", "men/63.jpg", "men/64.jpg", "men/65.jpg",
            "men/67.jpg", "men/69.jpg", "men/7.jpg", "men/70.jpg", "men/71.jpg",
            "men/72.jpg", "men/77.jpg", "men/78.jpg", "men/8.jpg", "men/80.jpg",
            "men/82.jpg", "men/84.jpg", "men/86.jpg", "men/88.jpg",
            "men/91.jpg", "men/92.jpg", "men/95.jpg", "men/96.jpg",
            "men/98.jpg", "men/99.jpg", "women/0.jpg", "women/1.jpg",
            "women/11.jpg", "women/13.jpg", "women/14.jpg", "women/15.jpg",
            "women/16.jpg", "women/18.jpg", "women/20.jpg", "women/22.jpg",
            "women/23.jpg", "women/26.jpg", "women/27.jpg", "women/31.jpg",
            "women/32.jpg", "women/33.jpg", "women/34.jpg", "women/38.jpg",
            "women/39.jpg", "women/41.jpg", "women/42.jpg", "women/44.jpg",
            "women/46.jpg", "women/47.jpg", "women/48.jpg", "women/51.jpg",
            "women/53.jpg", "women/54.jpg", "women/55.jpg", "women/56.jpg",
            "women/57.jpg", "women/58.jpg", "women/6.jpg", "women/60.jpg",
            "women/61.jpg", "women/62.jpg", "women/63.jpg" };
    static String[] names = new String[] { "Sylvia Burke", "Hop Sawyer",
            "Rhiannon Hancock", "Zelda Stein", "Ariana Marks", "Aspen Holman",
            "Athena Hartman", "Cameran Jacobson", "Tamara Keith",
            "Wesley Stanley", "Kaitlin Barton", "Kibo Black", "Vincent Meyers",
            "Cullen Odonnell", "Nita Pruitt", "Evan Franklin", "Gray Phelps",
            "Vivien Wagner", "Merritt Robles", "Olivia Clark", "Irma Mercado",
            "Marah Harrell", "Lara Vargas", "Alan Ware", "Ezekiel James",
            "Hanna Howard", "Chiquita Stevens", "Dale Meadows",
            "Dominic Sanchez", "Sopoline Coleman", "Basil Hobbs", "Plato Kline",
            "Lareina Beach", "Jeremy Moses", "Wyoming Mcneil", "Karen Boone",
            "Ryder David", "Germaine Harmon", "Lila Cobb", "Stuart Chen",
            "Hop Mcguire", "Adena Smith", "Drew Wyatt", "Anika Ellison",
            "Martena Barnes", "Daria Benson", "Imogene Sanders", "Allen Owens",
            "Grace Head", "Colorado Barrett", "Colleen Carroll", "Daryl Day",
            "Madeson Garrett", "Chancellor Ford", "Haviva Phillips",
            "Jael Stevens", "Emma Guy", "Montana Watkins", "Rudyard Gutierrez",
            "Kirestin Mann", "Susan Hurst", "Luke Buckner", "Plato Yang",
            "Dara Bradford", "Irene Moreno", "Blaze Flores", "Chadwick Kemp",
            "Felicia Delacruz", "Idona Hatfield", "Sharon House",
            "Cheryl Bradley", "Yeo Rodriquez", "Jessamine Jackson", "Iris Park",
            "Maya Sherman", "Damian Gutierrez", "Yoshio Contreras",
            "Pearl Conner", "Uta Steele", "Winifred Mejia", "Pearl Morrow",
            "Kiara Delgado", "Kuame Knox", "Kaseem Sharp", "Rae House",
            "Hillary Odonnell", "Leonard Gilbert", "Barbara Trevino",
            "Rebecca Potter", "Alan Fuentes", "Ali Saunders", "Owen Vaughn",
            "Vivian Jackson", "Serena Campos", "Timothy Ratliff",
            "Hamilton Rice", "Madaline Summers", "Hope Rose",
            "Marshall Stanton", "Nero Camacho" };

    static String[] texts = new String[] {
            "Have you ever looked at the last few loads of dirty laundry and considered just throwing them away??",
            "If the party really was that great, you probably wouldn't have taken the time to update your Facebook status on how great the party is.",
            "My mom wasn't the best cook. If a piece of food fell on the floor, the dog would come over pick it up and stick it back to my plate.",
            "Dear Self,",
            "Customer service agents are like deaf people who go on answering questions that no one has asked them.",
            "Vacuum Cleaner out of order.", "In Japan it's called Pranking.",
            "I used to like to get glue on my fingers so I could peel it off when it dried. I dunno why I brought that up, but I know I'm not alone here.",
            "Denial 2. Anger 3. Bargaining 4. Depression 5. Acceptance......... The 5 stages of buying gas.",
            "pushing the revolving door the wrong way took quite a bit of effort.",
            "Your inspirational statuses are uplifting my stomach content. ",
            "Me, walking: \"Pedestrians  ALWAYS have the right of way!\"",
            "you're the type of guy I'd make a sandwich for",
            "Sometimes I say \"Beetlejuice\" three times so I can use the carpool lane.",
            "Driving would be much more entertaining if there were no yellow lights.",
            "On October 3rd, he asked me what day it was",
            "Cop: Did you see how fast you were going? Me: Um, no i was too busy slamming on my brakes when i saw you....",
            "There are two theories to arguing with women. Neither one works.",
            "Grocery stores could save me a lot of time and effort by adding an \"All the stuff you can microwave\" aisle.",
            "You know it's good pizza when the grease soaks through the table.",
            "Don't look unless you're prepared to see.",
            "Mitt Romney: America can't afford 4 more years of Obama's failed policies. It's time to try Bush's failed policies again.",
            "Frustrating to know I'll never experience the exhilaration of getting to meet me. ",
            "You'd be surprised at all of the \"that's what she said\" jokes you can make if you watch 5 minutes of a little kids show.",
            "If I'm ever in a movie that requires me to cry, I will just pull a nose hair. WTF are they attached to?",
            "My first thought at a sketchy gas station is always \"I hope I don't get robbed,\" followed immediately by, \"oh wait, I don't have any money.\"",
            "Texts that piss me off:",
            "P. Diddy woke up this morning feelin like me.",
            "The worst part about marathons is going potty in your shorts, but I refuse to risk losing my spot and miss seeing my favorite runners go by.",
            "Thank god Will Smith's daughter got that record deal so I can quit worrying about how that family is going to get by in this recession.",
            "Bathroom wall: Can I get a witness? Written below: I don't know. Are you going to do anything worth watching?",
            "The rulers of the Ottoman Empire must have had plenty of places to put their feet up.",
            "*Reports your selfie as abusive*",
            "I think, therefore we have nothing in common.",
            "I was watching a show about how to survive an apocalypse, who the fuck wants to survive that? I couldn't even go back to dial up",
            "Look I'm sorry about your lamp but automatic karate is a serious disease.",
            "No meal tastes as delicious as the meal that someone else cooks.",
            "I wear an eye patch when I download music illegally.",
            "I wonder if people with eye patches because thought it was all fun and games.",
            "Can't we all just hit a bong?",
            "Taylor Swift seems like the kind of girl who would post her horoscope to Facebook every day.",
            "Every morning: get dressed a little, lay down, get dressed a little more, lay down.",
            "Kanye West must feel very conflicted right now. He's excited Kim is pregnant, but deep down he knows Beyonce had the best baby of all time.",
            "Let's just cut the bullshit. Seriously do you want a piece of bullshit? Your piece of bullshit can be bigger than mine. I've had enough bullshit for the day. ",
            "Having people over for dinner tonight. They asked what they could bring. I said dinner.",
            "If you are someone who insists on talking on the phone rather than texting, I'm sorry but, we can't be friends.",
            "Grandma is so sweet. She wrapped a gift for my lady that stayed over last night and put it under the tree.",
            "A group of mistakes is called a life.",
            "Cold weather can trick your body into missing someone who's terrible for you.",
            "I know I need to clean my room when my friends start making hoarder jokes. ",
            "Mr. Boombastic wasn't really all that fantastic. ",
            "Status stalker : sending people to corners since 2009",
            "I used to live in a residential building until a few hookers moved in on the 4th floor - now it's a commercial building.",
            "If you were nothing, I would definitely be doing you right now.",
            "Jersey Shore just got cancelled. Clearly an act of God. Your move, atheists.",
            "Shit. There's no cream, I shouldn't put butter in my coffee right?",
            "When picking a ringtone, ask yourself: \"How embarrassed will I be when this rings?",
            "Not remembering where I set my drink down must be the same feeling parents have when they lose their four year old at the mall.",
            "Dont smoke...there are cooler ways to die.",
            "Ke$ha: weak music choice, strong password choice.",
            "I got the new Kindle Fire and attached it to my iPad with an elastic string. PADDLE BALL!",
            "I just want to move to a planet where everyone is color blind and pizza and chocolate milk grows on trees.",
            "I just want someone to look at me the way I'm looking at this drive thru menu.",
            "Why can't we all just get a Long Island Iced Tea?",
            "I think the best thing about turning 100 would be getting 100 dollars from your Grandma.",
            "Reading Goosebumps is still cool right?",
            "I just saved a bunch of money on Christmas presents by discussing politics on Facebook!",
            "Women are like electricity. I don't know how they work, don't really care, and I'm generally helpless if they don't turn on instantly.",
            "Is in desperate need of a padded room and a Thorazine drip..",
            "I can never laugh at people less fortunate than me because they are so hard to find.",
            "Face down, back up, that's the way, I like to...send faxes.",
            "The Internet is alot like acient Egypt , people writing on walls and worshiping cats.",
            "I will never trust anyone enough to let them scroll through my photos unsupervised.",
            "Boy Meet's World is getting a spin-off called Girl Meets World and it's about Corey & Topanga's daughter. If you're not excited, I hate you.",
            "Throwing away a good relationship because of problems that can be worked out, is like throwing away a new car because of a flat tire...",
            "Walking away from someone you love is as easy as sneezing with your eyes open.",
            "Sometimes you can end up losing yourself trying to hold onto someone who doesn't care about losing you.",
            "If it was really a \"smart phone\" it would know to tell me to wash my hands before I touch it.",
            " Funny how things change with time, I used to hate spankings.",
            "Alcohol may be man's worst enemy, but the Bible says to love our enemies",
            "If pigs could fly imagine how good their wings would taste.",
            "Without coffee, I'm just a really tall 2 year old.",
            "Have you tried insulting each other until the romance comes back?",
            "I dont make fun of gays. I call my friends gay and make fun of them.", };

    public static Tweet createRandomTweet(int index) {
        Tweet t = new Tweet();
        Random random = new Random(index);
        t.setText("Tweet " + index);
        t.setAvatarUrl(
                "https://pbs.twimg.com/profile_images/632546599781068801/k48u50aR_bigger.png");
        if (random.nextInt(10) > 6) {
            t.setRetweets(random.nextInt(100));
        }

        t.setAuthor(names[random.nextInt(names.length)]);
        t.setAvatarUrl("https://randomuser.me/api/portraits/thumb/"
                + avatars[random.nextInt(avatars.length)]);
        t.setText(texts[random.nextInt(texts.length)]);
        return t;

    }

}
